# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt install -y ruby-full
    which ruby
    which gem
    sudo gem install wayback_machine_downloader
    which wayback_machine_downloader
    wayback_machine_downloader http://viewlyrics.com -d viewlyrics
  displayName: 'Prerequisites'
